### ISSUE TITLE
Variable in attachement part

### ISSUE THREAD

**Issue by jlaudenbach** [ThibaudDauce/mattermost-php#6]
It is not possible to use variables in attachment part of message
```php
$var = getSomeTextFromElsewere();

$message = new Message();
$message->attachment(function (Attachment $attachment) {
    $attachment->text($var);
});
```

**Comment by jlaudenbach** [comment]
Found a solution:

```php
$var = getSomeTextFromElsewere();

$message = new Message();
$message->attachment(function (Attachment $attachment) use ($var) {
    $attachment->text($var);
});
```

Maybe you can add this to your example in the README.md

**Comment by ThibaudDauce** [comment]
Hi,

Yes it's the solution. It's not a feature of my library but a PHP language feature. You should read https://www.php.net/manual/en/functions.anonymous.php

**Comment by jlaudenbach** [comment]
Thank you, 
I will dig a little deeper into this topic.

And thank you for making your package open source. Its quite easy to use.
